### ISSUE TITLE
Autosub finds no files

### ISSUE THREAD

**Issue by Boldhead** [BenjV/autosub#13]
I noticed that 2 weeks ago my autosub stopped getting subs. couldnt get it to work so removed it and did a fresh install. Problem now is that I entered the correct path, but it doesnt find any series. I dont get an error about no permissions or something like that. I dont see any error messages. Permissions on folder are good, autosub internal user has rights, reinstall doesnt fix the problem. Do you have any idea whats going on?

**Comment by Boldhead** [comment]
some more info, I got it running on a synology, folder is /volume1/Video/Series

**Comment by Boldhead** [comment]
Na 6 keer herinstalleren werkt het nu ineens wel, geen idee waarom maar goed, hij doetut!

**Comment by BenjV** [comment]
Heeft natuurlijk niets met instaleren te maken.
Autosub opnieuw installeren is een onzinnige aanpak.
Als er iets met de code gebeurd zou zijn zou hij namelijk onmiddellijk crashen.

Volgende keer even de debug log aanzetten en hier plaatsen.
