### ISSUE TITLE
Installing on a Mac

### ISSUE THREAD

**Issue by TonVH** [BenjV/autosub#15]
In the past I installed it on a Mac and it worked after also installing Cheetah.

So now I am trying to get it working on a different Mac and it won't work. I get the following error messages:

iMac:autosub-master tonio$ /\#Downloads/autosub-master/AutoSub.py 
/#Downloads/autosub-master/AutoSub.py: line 1: import: command not found
/#Downloads/autosub-master/AutoSub.py: line 2: import: command not found
/#Downloads/autosub-master/AutoSub.py: line 3: import: command not found
/#Downloads/autosub-master/AutoSub.py: line 4: import: command not found
/#Downloads/autosub-master/AutoSub.py: line 5: import: command not found
/#Downloads/autosub-master/AutoSub.py: line 6: import: command not found
/#Downloads/autosub-master/AutoSub.py: line 7: import: command not found
from: can't read /var/mail/uuid
/#Downloads/autosub-master/AutoSub.py: line 11: syntax error near unexpected token `('
/#Downloads/autosub-master/AutoSub.py: line 11: `base_path = os.path.dirname(os.path.abspath(__file__))'

Any suggestions where to look?

**Comment by BenjV** [comment]
Ja hij kan z'n modules niet vinden.
Je opstart directory is verkeerd.

Ook kan hij de python modules niet vinden dus het path naar je python installatie ontbreekt ook.
