### ISSUE TITLE
Twitter notifications

### ISSUE THREAD

**Issue by JonasL1** [BenjV/autosub#2]
Lately, I get a lot of tweets that are recognized as a weblink. This is not a problem, but the actual problem is that the beginning of the link (the series name) is very incompleted so I don't know which sub is downloaded unless I click on the link. See attached image, the third tweet is a tweet with actual text from autosub, the other 2 I just tried as possible solutions. They are not very optimal, just removing the srt could be a possible solution in most cases.
![2017-01-13_16-14-16](https://cloud.githubusercontent.com/assets/4752888/21934882/6f028d34-d9ab-11e6-8c5e-b494a13da04d.png)

**Comment by BenjV** [comment]
I shall replace the dots with a dot followed by a zero width character.
This will prevent twitter to interpret the filename as a weblink.

**Comment by JonasL1** [comment]
Ok, thankyou.

**Comment by BenjV** [comment]
New version (1.0.6) is released, please test if it is working as I expect.

**Comment by kboeckx** [comment]
I've tested this and now I see a "?" where you inserted the whitespace
![afbeelding](https://cloud.githubusercontent.com/assets/2222436/21954630/186e1856-da57-11e6-8d56-c1cce3ee1802.png)

Did you use the correct code for the zero width space ? see http://www.fileformat.info/info/unicode/char/200B/index.htm

**Comment by BenjV** [comment]
from the source
[code]
NonUrlName = subtitlefile.replace('.',u".\u200B")
[/code]
Shall I replace the dot with a space?

**Comment by kboeckx** [comment]
No, the dot and zero width spaces is what we want.

What encoding are you using for the variables 'NonUrlName' and 'message' in 'twitter.py' ?

**Comment by BenjV** [comment]
utf-8

**Comment by kboeckx** [comment]
Hi,

The python Twitter module and/or the Twitter API does not seems to handle unicode characters well
![afbeelding](https://cloud.githubusercontent.com/assets/2222436/21962049/150a520a-db1b-11e6-84ae-6c1d0c5f34d6.png)
-> Still the same issue

It's anoying that twitter resolves this to a hyperlink but it's more anoying with the '?'. So for now, I think it's best to rollback to:
`message = "%s downloaded from %s" %(subtitlefile, website)`

Thanks

**Comment by BenjV** [comment]
I will roll it back but I think the best solution will be to replace the dots in the filename with a space.
Then it is still readable and twitter will not treat it as a weblink.

**Comment by kboeckx** [comment]
OK, space is acceptable.
I don't know if the extention ".srt" is relevant. I you can remove it, it will be nicer.

I've change the code to
` message = "%s downloaded from %s" %(subtitlefile, website)
    message = message.replace('.srt','')
    message = message.replace('.',' ')
`
now it looks like:
![afbeelding](https://cloud.githubusercontent.com/assets/2222436/21965002/dd5c286a-db56-11e6-8fd0-82c43acd141c.png)

ok for me.

Greeting, 
Kris Boeckx

**Comment by JonasL1** [comment]
I also find it acceptable with a space, but then it would indeed be nicer without the srt.

**Comment by BenjV** [comment]
I remove the .srt and replace the dots with spaces.
I also added quotes around the subitle to separate the name from the rest of the text.

New version is available.

**Comment by kboeckx** [comment]
Look good
![afbeelding](https://cloud.githubusercontent.com/assets/2222436/21975446/075a17d2-dbcd-11e6-9d42-047028a9f887.png)

Thanks for support !
