### ISSUE TITLE
TheTVDB verification doesnt work/return result

### ISSUE THREAD

**Issue by Tweaqer** [BenjV/autosub#20]
After I updated the app to 1.1.9 I noticed the required thetvdb registration.
I entered my details and pressed verify, but I dont get a spinning thingy or a result like with Addic7ed or Opensubtitles.
Can you please make that happen? :)
Cheers

**Comment by BenjV** [comment]
Empty your browser cache.
That still has the old javascript which is changed.

**Comment by Tweaqer** [comment]
Awesome, that worked!
