### ISSUE TITLE
Setting "Allow Hearing Impaired subs"

### ISSUE THREAD

**Issue by gillesoorts** [BenjV/autosub#21]
Would it be possible to check when the setting "Allow Hearing Impaired subs" is working?

I've unchecked the option, but I keep on getting HI subs. I know the option isn't working on opensubtitles and subscene, I'll check other sources as soon I get a sub downloaded from them.

Thanks,
Gilles

**Comment by BenjV** [comment]
It is working on both Addic7ed and Opensubtitles.
On subscene and podnapisi not.
The problem is that a lot of sub uploaders don't mark the sub as Hearing Impaired.

Also all the web-dl always have English subtitles with Hearing Impaired subs embedded in the .mkv container.

**Comment by gillesoorts** [comment]
Thanks for the info!

I created the Issue because I recently occurred problems with a specific subtitle. AutoSub downloaded a HI version of the subtitle for Ray Donovan S05E09 from Subscene.

I checked the website manually, and there are both HI and non-HI versions of the subtitles (check this [screenshot](https://www.dropbox.com/s/n46sc76szw8ronk/Ray%20Donovan.png?dl=0)). But maybe this isn't available in their API?

**Comment by BenjV** [comment]
Subscene and Podnapisi don't have an API.
Those sites are searched via subtitle seeker and they don't have the possibility to select on Hearing Impaired.
Besides that, most of the subs on those sites are also found on Opensubtitles and/or Addic7ed, so I would suggest (as I myself do) to skip searching on subscene and podnapisi.

**Comment by gillesoorts** [comment]
Thanks for the info, I disabled Subscene and Podnapisi. 

It might be helpful to mention that these two sources don't support the HI option in an additional information popup for the "Allow Hearing Impaired subs" option?
