### ISSUE TITLE
Option to set permissions for new subtitle file

### ISSUE THREAD

**Issue by l-t-k** [BenjV/autosub#22]
New subtitle files are created with '0666' (read and write for owner, group and others). I like to set it to '0644'. That is the default unix creation mode so maybe that should be the default for autosub as well?

**Comment by BenjV** [comment]
I will look into that.

I just use the standard open to create the file and  Python uses 0666 for that.
(standard os.open).
I could change it but that will create most likely a lot of problem to less technical users.
Maybe I should just copy the privileges that the video file has, but maybe I should put in a possibility for the user to choose there own settings.
Let me come back to this.

In the mean time you could make use of a postprocessing script to that for you.

**Comment by BenjV** [comment]
The new version has this functionality.

**Comment by l-t-k** [comment]
Thanks!
