### ISSUE TITLE
Option to set config.properties, database.db and logfile location?

### ISSUE THREAD

**Issue by l-t-k** [BenjV/autosub#23]
I'm missing an option to specify a different than the default app location for the files mentioned. I now it's possible to set another config.properties location, but this is not working if the config.properties still needs to be generated (like on first start ups).

Option like nzbhydra does:
--config, --database and --logfile

I'm trying to make a dockerfile with the linuxserver.io base image for this app. That's why it's needed.

**Comment by BenjV** [comment]
It is possible to use a different config.properties via the -c commandline argument, but then you have to supply one. 
But not the database and logfile.
They are located where autosub is installed.
Why should you want to put them elsewhere?

**Comment by kooimens** [comment]
Because of how docker works. Pulling a new image will destroy the old container and builds a new one. Files like config.properties, database.db and maybe logfiles should be persisted. A location within the container can be set as a volume and will remain on disk if the container is deleted/updated.

**Comment by BenjV** [comment]
Stupid solution of docker, but in my opion is docker a complete waste of time.
The correct solution should be that an docker  update process would first backup configuration data, before installing a new docker image.

But besides that, I can accommodate you.
I can change autosub so it will use the location of the folder specified on the commandline -c option for all three files.
Would that be suffient?

**Comment by kooimens** [comment]
That will be sufficient! Thanks in advance!

**Comment by BenjV** [comment]
Ok I will build it in the next release.

**Comment by BenjV** [comment]
I have released a new version with this functionality.

**Comment by l-t-k** [comment]
Thanks! Works perfect
