### ISSUE TITLE
Not starting on 0.0.0.0

### ISSUE THREAD

**Issue by ikkeenjij36** [BenjV/autosub#25]
Hi all and first happy new year.
I have a problem that autosub won't start.
I get this error in the log:`01-01 15:01:12 INF main        :PID is: 26814
01-01 15:01:12 INF start       :Starting CherryPy webserver
01-01 15:01:17 ERR start       :Could not start webserver. Error is: Port 9960 not free on '0.0.0.0'`
How can i solve this?
Nothing has changed just got on this issue this morning.
I know that it's the port that doesn't open but where and how to activate it?

**Comment by TRaSH-** [comment]
Isn't that port taken by another program ?
Would it work if you edit manually the config file ?

**Comment by BenjV** [comment]
The port is in use so Autosub is still runnen and you are trying to start it again.

**Comment by ikkeenjij36** [comment]
Okay and how do is solve it then cause the appcenter on my syno says its not running

**Comment by BenjV** [comment]
Reboot your Nas but wait till I have made a new package.
This one is having trouble with the latest DSM updates.

**Comment by ikkeenjij36** [comment]
Resolved by updating
