### ISSUE TITLE
Criteria for skipping episodes

### ISSUE THREAD

**Issue by gillesoorts** [BenjV/autosub#27]
What are the criteria for looking for episodes in the new release? Very few subtitles are looked for in the new version (i.e., a lot of episodes greyed out).

I guess it has something to do with missing information (release group,...) and only the most recent shows? But it's not very transparant yet, so it would be nice to include some information on the process somewhere (on the settings page maybe, along with some settings to determine a few search parameters?)

**Comment by TRaSH-** [comment]
It's explained in the readme and also in autosub if you check the info in the top.

**Comment by gillesoorts** [comment]
All right, hadn't thought of looking there because the README says changes for version 1.2.0. Thanks!

**Comment by TRaSH-** [comment]
Zoek schema voor oude video's is nu:
Tussen 0 en 4 weken wordt altijd gezocht naar de sub.
Tussen 4 en 16 weken wordt er een keer per week gezocht op een dag gezocht
Ouder dan 16 weken wordt er een keer per 4 weken gezocht op een dag gezocht.

**Comment by DaveDrupsteen** [comment]
@BenjV 
Perhaps an option to force a check or a list of shows that should always be searched regardless of age.
I recently added a few "older" shows which are greyed out and weren't added to the search so I had to get them from Addic7ted manually. 

It's not an issue of its not possible but it would be nice :)

**Comment by gillesoorts** [comment]
I had the same problem today. Might be able to solve this by calculating the "age" of an episode by the date added to autosub instead of the file date?

**Comment by BenjV** [comment]
In the 1.2.18 version there is now a pull down command called Forced Search which override the date constrain used by the scheduled search.
