### ISSUE TITLE
Files on remote location

### ISSUE THREAD

**Issue by sepodele** [BenjV/autosub#3]
I have my files on a Western Digital NAS with the following address working fine in explorer.exe: \\10.0.0.100\Public\TV. However, when I use that in Auto-Sub I get the following:

2017-03-07 19:20:03,221 INFO  checkSub: Nothing to search for.
2017-03-07 19:20:03,220 INFO  scanDisk: Finished round of local disk checking
2017-03-07 19:20:02,668 INFO  scanDisk: Starting round of local disk checking at \\10.0.0.100\Public\TV

Any ideas?

**Comment by TRaSH-** [comment]
I think you need to add a extra "\" in front.

**Comment by BenjV** [comment]
an extra \

**Comment by sepodele** [comment]
Sorry. I did use \\ but copy pasted \. I've also tried mapping it to Z:\ but it still doesn't work. Something to do with rights to access the network disk perhaps?

**Comment by sepodele** [comment]
Ok, the text editor here removes one of the \\. I did try with \\\.

**Comment by BenjV** [comment]
If it was an access rights problem then the log would have gave you an error message..
Now it seems that autosub finds the folder but does not find any video files there, nor does it find subfolderes there.
Maybe you can switch on the debuglog in autosub to see if there is more info on this.

**Comment by sepodele** [comment]
That was a great suggestion. I didn't know I could enable debug log. Had a bunch of 'Filespec does not meet minmatchscore so skipping this one'. Apparently when I changed to remote disk I started using very little info in the file name and had minmatchscore set to source. Should be ok now. Thanks!

**Comment by BenjV** [comment]
Just Source as minmatch score is normally the best setting
