### ISSUE TITLE
HDTV vs HD.TV

### ISSUE THREAD

**Issue by gonijn** [BenjV/autosub#31]
Some series filenames still have HD.TV instead of HDTV resulting in a lot of not qualified to search for. Is there any way to add this mapping in the app?

**Comment by BenjV** [comment]
That's a problem, because the point (.) is the seperator between the various specification parts and autosub will see HD.TV as a specificatie of quality namely "HD" and not as the source specifier "HDTV".

I will see if I can make a workaround to this problem.

**Comment by BenjV** [comment]
fixed in version 1.2.18
