### ISSUE TITLE
RootPath error when using username and password in Web config

### ISSUE THREAD

**Issue by Tjiet** [BenjV/autosub#33]
When a username and password is defined in the config, autosub starts with an error:

_AutoSub: Initializing variables and loading config
AutoSub: Starting output to log. Bye!
Traceback (most recent call last):
  File "AutoSub.py", line 132, in <module>
    exit(main())
  File "AutoSub.py", line 129, in main
    autosub.Scheduler.start()
  File "/var/AutoSub/autosub/Scheduler.py", line 157, in start
    StartCherrypy()
  File "/var/AutoSub/autosub/Scheduler.py", line 113, in StartCherrypy
    'tools.staticdir.root': RootPath,
UnboundLocalError: local variable 'RootPath' referenced before assignment_

If the username and password are removed from the config.properties it starts ok.

Build 1.2.18

**Comment by BenjV** [comment]
Sorry a mistake in the indent of an if statement
I shall correct it amd release a new version today.

Thanks for informing me of this.

**Comment by Tjiet** [comment]
Thx, let me know when it is released
		

		
	





On Mon, Mar 5, 2018 at 10:41 AM +0100, "BenjV" <notifications@github.com> wrote:












Sorry a mistake in the indent of an if statement

I shall correct it amd release a new version today.


Thanks for informing me of this.

**Comment by BenjV** [comment]
New version (1.2.19) is release where this is fixed.

**Comment by Tjiet** [comment]
I can confirm that it works again ! great work !
