### ISSUE TITLE
webinterface on mobile device doesn't show topbar

### ISSUE THREAD

**Issue by Tjiet** [BenjV/autosub#34]
When opening the interface on a mobile device it show the mini view, when selecting exit mini it show the normal interface, execpt without a top bar

![autosub](https://user-images.githubusercontent.com/6305901/36974835-6746ecba-2078-11e8-87cb-08cbf6645104.jpg)

**Comment by BenjV** [comment]
That's a problem of the browser on the mobile device.
Some browser don't scale good enough.
If you rotate your device you most likely get a better result in landscape mode.

That's why the mini version is available.

**Comment by Tjiet** [comment]
but in previous builds i could open up the settings from the topbar
and in landscape there are no topbar items, just empty

iphone X

**Comment by BenjV** [comment]
I needed a little bit more room to display al the items in the wanted list so I made it a little wider.
Iphone's browsers don't play nice scaling websites. Sorry.

My android tablet and phone with Chrome do not have this problem.

**Comment by Tjiet** [comment]
Thx for clarifying  that

		

		
	





On Mon, Mar 5, 2018 at 3:21 PM +0100, "BenjV" <notifications@github.com> wrote:












I needed a little bit more room to display al the items in the wanted list so I made it a little wider.

Iphone's browsers don't play nice scaling websites. Sorry.


My android tablet and phone with Chrome do not have this problem.

**Comment by BenjV** [comment]
I found the problem.
The button that is used to display the menubar if the screen is collapsed (as on a phone) was faulty in the template.
I will fix this in a new release (1.2.21) later this day.

**Comment by Tjiet** [comment]
Great work !
