### ISSUE TITLE
auto-sub not updating and nothing wanted

### ISSUE THREAD

**Issue by MrMdemiC** [BenjV/autosub#36]
Hi,

I see that there been some updates here and i wanna stay up to date on my synology nas.
Currently i am running DSM Version: DSM 6.1.5-15254 Update 1
And auto-sub version: 1.2.19 (1.2.22)

If i use the command Check Version i see: http://puu.sh/zJ0mT/c85579be17.png
And if i use Update its just trying to refresh the page and doing nothing?

Is there an other way update?

Besides the update problem there is nothing in my wanted list.
I have changed nothing on the settings/series folder.

Is there anyway to fix it?

Thank you :)

Greetings MrMdemiC

**Comment by BenjV** [comment]
There were some problems with that version.
Just download the new package and do a manual install.
Je package will be updated then and the autosub version in the same time.
All settings, logs and database will be preserved.
You can find the package here:
https://github.com/BenjV/SYNO-packages/raw/master/AutoSub%20DSM6%20noarch.spk

**Comment by MrMdemiC** [comment]
Sorry for the late reply but it works again :D thanks alot man! i love this program!! 

Gonna run it on a windows server soon ;) my nas is to slow now xD
