### ISSUE TITLE
HTTPSConnectionPool(host='api.thetvdb.com', port=443): Read timed out.

### ISSUE THREAD

**Issue by malinwa001** [BenjV/autosub#37]
Hello got this error for several days.

```
17-03 18:03:20 ERR GetTvdbId      :Tvdb returnd an error: Resource not found
17-03 18:02:30 ERR GetToken       :HTTPSConnectionPool(host='api.thetvdb.com', port=443): Read timed out. (read timeout=10)
```

My TheTVDB  settings are correct. Somethimes when i do the check on the settings page it works.
When i start the search wright after it did't do a thing but putting out these errors.

**Comment by BenjV** [comment]
It is a connection problem on the TVDB server-site judging to the error.
The server does not respond within the read timeout.

Which version of autosub are you using?

**Comment by malinwa001** [comment]
Latest 1.2.22

Having this for several days now

**Comment by BenjV** [comment]
I cannot reproduce this problem on my windows test environment nor do I have this problem on my Synology Nas.
Also nobody else has experienced this problem, so there must be something wrong with your network or internet connection if you keep having this connection timeout.

Have you checked the default gateway and DNS settings of your device or maybe a firewall setting?

**Comment by BenjV** [comment]
This is not the same but completely different.
Here TVDB return an error indicating that the showname could not be found.
So maybe you have a non existing showname.

Please post the full filename of the videofile you are trying to find a sub for.
