### ISSUE TITLE
Error trying to look at logfile

### ISSUE THREAD

**Issue by WeirDave** [BenjV/autosub#38]
Attempting to look at the log file v1.2.22:

`Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/QAutoSub/.AutoSub/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/share/CACHEDEV1_DATA/.qpkg/QAutoSub/.AutoSub/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/QAutoSub/.AutoSub/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/QAutoSub/.AutoSub/autosub/WebServer.py", line 662, in viewLog
    return str(tmpl)
  File "/share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages/Cheetah/Template.py", line 1005, in __str__
    rc = getattr(self, mainMethName)()
  File "_share_CACHEDEV1_DATA__qpkg_QAutoSub__AutoSub_interface_templates_viewlog_tmpl.py", line 145, in respond
NotFound: cannot find 'logentries'`

**Comment by BenjV** [comment]
Check to see if there is a logfile and if the user which you use to run autosub had read/write access to that file/folder.
Did you specify your own logfile in the config?

**Comment by WeirDave** [comment]
The config file is the default location:
/share/CACHEDEV1_DATA/.qpkg/QAutoSub/.AutoSub/AutoSubService.log

If I WinSCP to that location I can see the file and it's contents but the button doesn't work

**Comment by BenjV** [comment]
No movie support, just TV shows.

So autosub writes the logfile but the webserver (the gui) cannot read it.
Is the default directory were you start autosub the same as were the logfile is and how about the read/write settings?

**Comment by WeirDave** [comment]
It may have been the read write settings on the folder but I would think you would set those on install. Anyway I ended up uninstalling and using subzero a plug in for Plex because I need movies too. Thanks for your help and best of luck!

**Comment by BenjV** [comment]
Autosub is just a python application, installing is left to the user and so is setting the privs if needed.

**Comment by WeirDave** [comment]
Perhaps, including what permissions need to be changed in some sort of wiki would be helpful for future users?

**Comment by BenjV** [comment]
Duh.
Read/write privs for all folders you set in the configuration settings and of the folder you installed autosub in.
Seems to me very obvious and you are the first with this kind of problem.

**Comment by WeirDave** [comment]
Should the Read / Write be set to "0755" or "0777"?

**Comment by BenjV** [comment]
Ok the only other explanation I can think of is that some of the software got corrupted..
You are the only user who has this problem, so it is either in the environment or the source is corrupted.
