### ISSUE TITLE
Can you add support for Python 3?

### ISSUE THREAD

**Issue by sepodele** [BenjV/autosub#4]
There are all kinds of errors when trying to run it with Python 3. Can you fix? :)

**Comment by TRaSH-** [comment]
You can install both versions of python at the same time,
I also got python 3 and python 2 running

**Comment by sepodele** [comment]
Yeah. But it's less convenient in Windows with the PATH etc. Having only one installed I can run scripts.pyw like executables. But having Python 2.7 installed as well, I have to execute Autosub with python27.exe etc.

**Comment by BenjV** [comment]
I have no plans to migrate to python 3.
I don't see the problem runnen both python 2 and python 3 on the same machine and you can still use pythonw.exe from the python 2 distribution.
Just put the full path in front of the pytonw.exe command.

I don't see the logic for me to put a lot of work into converting autosub to python 3, just so you don't have to put the full path in your commandoline.

**Comment by sepodele** [comment]
Yeah, OK. I managed to make a shortcut that starts AutoSub with Python 2.7, so I can live with that.

However, I'm getting this: ERROR  subseeker: Failed to get the downloadpage from subscene.com. Message : [Errno 1] _ssl.c:507: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

I hope it's a temporary bug with subscene as disabling subscene in options works.

**Comment by BenjV** [comment]
Make a little .bat file that first does a change directory where autosub is located and then start autosub.

**Comment by sepodele** [comment]
Made a .bat file like this:

cd C:\Dropbox\Various\#Applications\Auto-Sub\
C:\Python27\pythonw.exe autosub.py

Still getting the error.

**Comment by BenjV** [comment]
Check if the file  "C:\Dropbox\Various#Applications\Auto-Sub/library/requests/cacert.pem" exists.
Which version of autosub are you using.

**Comment by sepodele** [comment]
Yeah, it exists. And version 1.1.2.

**Comment by sepodele** [comment]
Not sure if related, but also getting Pushbullet: notification failed. and I've double checked that the API key is the same I use for other apps.

**Comment by sepodele** [comment]
I ran it from cmd.exe to look for errors. This is what I got:

C:\Dropbox\Various\#Applications\Auto-Sub\library\requests\packages\urllib3\util\ssl_.py:334: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
C:\Dropbox\Various\#Applications\Auto-Sub\library\requests\packages\urllib3\util\ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning

**Comment by sepodele** [comment]
Upgraded to newest 2.7 version of Python and now I got no errors and Pushbullet started working again. Thanks for the patience. You can close the issue. :)
