### ISSUE TITLE
Fallback to english for all series but skip dutch for some

### ISSUE THREAD

**Issue by Sven79** [BenjV/autosub#48]
I have the following settings:
![image](https://user-images.githubusercontent.com/31131918/46858706-30e45580-ce0c-11e8-873f-870273917c56.png)

And also I have some series mentioned in "Skip Folder Dutch"

But apparently this implies that the series mentioned in "Skip Folder Dutch", are not searched for at all.

I would like to search for dutch subs for almost all series (with fallback to English), but for a few series, I want to search for English only (as dutch subs will probably never be found but it keeps counting towards de API-count). 

I think it will work if I check to also download English subs, but if a dutch sub is available, there is no need to download the English sub for that series. And if i were to add that series to Skip Folder English, I guess the fallback to English will not work anymore.

Is there a way to search for all series for only Dutch subs, fallback to English, but also search for some series for English subs only (without downloading English subs for other series, where the Dutch sub is available/downloaded)

Regards,

**Comment by BenjV** [comment]
No that's not possible.
But via the age rules build into autosub, old video will be search for less and less if they get older, so I don't think it is a problem.

Also API count is always "per day/downloaded" and not per "searched for".
