### ISSUE TITLE
Internal server error view log

### ISSUE THREAD

**Issue by ropi** [BenjV/autosub#5]
Since 1.1.3 I'm getting an internal server error when clicking on log.

**Comment by BenjV** [comment]
This is very little info to work with.
Most likely the update failed to put a new template file in place.
Take a look at the logfile to see if the update failed.

On what kind machine are you running autosub?

**Comment by ropi** [comment]
I'm sorry, you're right 😀
It is running on a Synology DS414 with the latest version of DSM installed.
The newly installed version of autosub is working fine and doing its job.
Only thing I noticed is when I click 'Log' that it shows the server 500
error.
I'm not home now, so I can't open any other log, but I'm sure the update
went ok.

Kind regards,
Roger

Op zo 14 mei 2017 11:45 schreef BenjV <notifications@github.com>:

**Comment by BenjV** [comment]
The only change I made at the logfile is the template file en the error seams to indicate the error is to be found in a missing or wrong (or old) template.
It is the viewlog.tmpl file.

**Comment by ropi** [comment]
Should I try to delete the template file? Will a new file be created
automatically?

Op zo 14 mei 2017 12:57 schreef BenjV <notifications@github.com>:

**Comment by BenjV** [comment]
Best is to download the zipfile from GitHub and replace just that viwelog.tmpl with the one from the zip file.
You don't have to stop autosub for that.
Just try to view the log afterwards.

**Comment by ropi** [comment]
Thanks, I will try that.

Op zo 14 mei 2017 13:39 schreef BenjV <notifications@github.com>:
