### ISSUE TITLE
addic7ed koppeling down

### ISSUE THREAD

**Issue by DaveDrupsteen** [BenjV/autosub#50]
Hi,

Het lijkt erop dat addic7ed.com https geactiveerd heeft met een 302 redirect. Hierdoor kan autosub niet meer inloggen.

Is dit te fixen door zelf wat aan te passen of kan je je code updaten?

Grtz,
Dave

**Comment by BenjV** [comment]
Addic7ed heeft een recaptcha V2 op hun login pagina gezet.
Dat levert dus deze problemen op.
Ik heb nog geen mogelijkheid gevonden dat te omzeilen.

Ze beloven dat ze met een API komen, dus als die er komt zal ik heb gaan gebruiken.
Tot dan helaas geen Addic7ed vanuit autosub.
