### ISSUE TITLE
How is multi episode packs handled?

### ISSUE THREAD

**Issue by hotio** [BenjV/autosub#8]
On subscene.com you can download subtitle packs for full seasons, it downloaded one such pack, however the resulting srt was only 7kb in size and completely wrong/not in sync.

```
INFO  checkSub: Searching downloadlink(s) for Better Call Saul - S01E01 - better.call.saul.s01e01.hdtv-720p.ac3.5.1.x264-killers, for ['Dutch', 'English']
INFO  getSubLinks: Found 2 ENGLISH subs which matched the min match score.
INFO  downloadSubs: Subtitle Better.Call.Saul.S01E01-10.HDTV.x264-KILLERS is downloaded from subscene.com
```

**Comment by BenjV** [comment]
Autosub is expecting a zipfile with only one sub in the zip.

There is no standard way how such packs are named, so it is difficult to recognize them as a pack.
Subscene does not support an API so everything has to be done with screen scraping.
I will look into it how to recognize and skip those packs from being downloaded.

**Comment by hotio** [comment]
Sounds good

**Comment by BenjV** [comment]
Done
